### ISSUE TITLE
Investigate: Retrieval is not working properly

### ISSUE THREAD

**Issue by Inamul-Hassan** [Inamul-Hassan/FlowRAG#6]
Below are few sample questions to which we didn't get any response, it simply said that retrieved context didn't contain any information about the query.

"Who is the author?", "Who is paul graham?", "how many grad school did the author apply to?"

But clearly there are information about the question is the text.

Action Items:
> Try enabling verbose/show_progress and check at the retrieved context
> Maybe test with different retriever/query_engine
> Retest retriever

**Comment by vishal-sr** [comment]
Retrieval works fine now. But let's test in production with application. We can close this for now.
